---
- hosts: localhost
  vars:
    username: sirianni
  become: yes
  pre_tasks:
    - name: Add localhost to /etc/ansible/hosts
      lineinfile:
        dest: /etc/ansible/hosts
        state: present
        regexp: '^localhost'
        line: 'localhost ansible_connection=local'
  roles:
    - sudo
    - ssh_keys
    - dotfiles
    - x1carbon
    - confluent
  tasks:
    - name: Install basic utilities
      package:
        name:
          - vim
          - terminator
          - build-essential
          - curl
          - httpie
          - xclip
          - apt-file
          - cifs-utils
        state: present
    - name: Install chrome-gnome-shell
      package:
        name: chrome-gnome-shell
        state: present
    - name: Install system monitor dependencies
      package:
        name:
          - gir1.2-gtop-2.0
          - gir1.2-networkmanager-1.0
          - gir1.2-clutter-1.0
    - name: Install Java
      package:
        name: default-jdk
        state: present
    - name: Install NodeJS
      include_role:
        name: geerlingguy.nodejs
      vars:
        nodejs_version: 11.x
    - name: Install basic utilities from NPM
      become: no
      npm:
        name: "{{ item }}"
        global: yes
      loop:
        - tldr
        - npx
    - name: Install Docker
      include_role:
        name: geerlingguy.docker
      vars:
        docker_users: [ sirianni ]
        docker_apt_repository: "deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable"
    - name: Install IntelliJ
      command: snap install intellij-idea-ultimate --classic
    - name: Install VS Code
      include_role:
        name: ngetchell.vscode