---
- hosts: localhost
  vars:
    username: sirianni
  become: yes
  pre_tasks:
    - name: Add localhost to /etc/ansible/hosts
      lineinfile:
        dest: /etc/ansible/hosts
        state: present
        regexp: '^localhost'
        line: 'localhost ansible_connection=local'
  roles:
    - sudo
    - ssh_keys
    - dotfiles
    - x1carbon
    - confluent
  tasks:
    - name: Install basic utilities
      package:
        name:
          - vim
          - terminator
          - build-essential
          - curl
          - xclip
          - apt-file
          - cifs-utils
        state: present
    - name: Install chrome-gnome-shell
      package:
        name: chrome-gnome-shell
        state: present
    - name: Install system monitor dependencies
      package:
        name:
          - gir1.2-gtop-2.0
          - gir1.2-networkmanager-1.0
          - gir1.2-clutter-1.0
    - name: Install Java
      package:
        name:
          - openjdk-8-jdk
          - openjdk-8-source
          - openjdk-11-jdk
          - openjdk-11-source
        state: present
    - name: Install NodeJS
      include_role:
        name: geerlingguy.nodejs
      vars:
        nodejs_version: 11.x
        npm_config_prefix: /home/{{ username }}/npm
        nodejs_npm_global_packages: [ tldr, npx ]
    - name: Install Docker
      include_role:
        name: geerlingguy.docker
      vars:
        docker_users: [ sirianni ]
        docker_apt_repository: "deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable"
    - name: Install IntelliJ
      command: snap install intellij-idea-ultimate --classic
    - name: Install VS Code
      include_role:
        name: ngetchell.vscode
    - name: Install hub (GitHub CLI)
      block:
        - name: Add cpick PPA
          apt_repository:
            repo: ppa:cpick/hub
            codename: bionic
        - name: Install hub from PPA
          package:
            name: hub
            state: present
    - name: Install additional utilities
      package:
        name:
          - cloc
          - httpie
          - gist
          - ack
        state: present
    - name: Install python packages
      package:
        name:
          - python3-venv
          - python3-pip
        state: present
    - name: Increase file watcher limit
      copy:
        src: 20-file-watchers.conf
        dest: /etc/sysctl.d/